name: "publish to npm"
on: workflow_dispatch
jobs:
    main:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [14]
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: ⎔ Setup node
              # sets up the .npmrc file to publish to npm
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  registry-url: "https://registry.npmjs.org"

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Configure git user
              run: |
                  git config --global user.email ${{ github.actor }}@users.noreply.github.com
                  git config --global user.name ${{ github.actor }}
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

            - name: ▶️ Run release
              run: npm run release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
